sudo: required
dist: trusty
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
  - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
  - sudo apt-get update
  - sudo apt-get -y install qt55declarative qt55quickcontrols qt55graphicaleffects qt55tools qt55svg
  - sudo apt-get -y install qt56declarative qt56quickcontrols qt56graphicaleffects qt56tools qt56svg
  - sudo apt-get -y install xvfb

script:
  # Test on Qt 5.5
  - source /opt/qt55/bin/qt55-env.sh
  - qmake . && make && sudo make install
  - xvfb-run -a -s "-screen 0 800x600x24" make check
  - git clean -xfd

  # Test on Qt 5.6
  - source /opt/qt56/bin/qt56-env.sh
  - qmake . && make && sudo make install
  - xvfb-run -a -s "-screen 0 800x600x24" make check
  - git clean -xfd

notifications:
  slack: papyros:Z7PeY2Y4mh0GWPoypZZNLd3D
